var caldef2 = {
	firstday:0,
	dtype:'dd/MM/yyyy',
	width:250,
	windoww:270,
	windowh:170,
	border_width:0,
	border_color:'#fefefe',
	dn_css:'clsDayName',
	cd_css:'clsCurrentDay',
	wd_css:'clsWorkDay',
	tw_css:'clsWorkDay',
	we_css:'clsWeekEnd',
	wdom_css:'clsWorkDayOtherMonth',
	weom_css:'clsWeekEndOtherMonth',
	wdomcw_css:'clsWorkDayOthMonthCurWeek',
	weomcw_css:'clsWeekEndOthMonthCurWeek',
	wecd_css:'clsWeekEndCurDay',
	wecw_css:'clsWeekEndCurWeek',
	highlight_css:'clsHighLight',
	headerstyle: {
		type:"comboboxes",
		css:'clsWorkDayOtherMonth',
		yearrange:[2005,2007]
	},
	monthnames: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
	daynames: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sa"],
	template_path:'',
	img_path:'img/'
};